Repository Linkode2024/Linkode2024_BE, pull requests merged in 2024-10, with the labels that each got.

#56 Refactor : 회원탈퇴시 CAPTAIN 인 스터디룸의 자료 삭제
  src/main/java/com/linkode/api_server/common/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/linkode/api_server/domain/data/Data.java
  src/main/java/com/linkode/api_server/repository/data/DataRepository.java
  src/main/java/com/linkode/api_server/service/DataService.java
  src/main/java/com/linkode/api_server/service/MemberService.java
  src/main/java/com/linkode/api_server/service/MemberStudyroomService.java
Labels: refactoring, Feature

#55 Refactor : 스터디룸 입장 코드 개선
  src/main/java/com/linkode/api_server/common/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/linkode/api_server/controller/StudyroomController.java
  src/main/java/com/linkode/api_server/service/InviteService.java
  src/main/java/com/linkode/api_server/service/StudyroomService.java
Labels: refactoring

#58 Fix : 스터디룸 삭제시 깃허브이슈 + 데이터 삭제 수정
  src/main/java/com/linkode/api_server/common/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/linkode/api_server/controller/StudyroomController.java
  src/main/java/com/linkode/api_server/repository/StudyroomRepository.java
  src/main/java/com/linkode/api_server/repository/data/DataRepository.java
  src/main/java/com/linkode/api_server/repository/githubIssue/GithubIssueRepository.java
  src/main/java/com/linkode/api_server/repository/memberstudyroom/MemberstudyroomRepository.java
  src/main/java/com/linkode/api_server/service/StudyroomService.java
Labels: fix
