Repository Linkode2024/Linkode2024_BE, pull requests merged in 2024-09, with the labels that each got.

#50 Refactor : 소셜로그인응답수정
  src/main/java/com/linkode/api_server/controller/LoginController.java
  src/main/java/com/linkode/api_server/domain/Member.java
  src/main/java/com/linkode/api_server/dto/member/LoginResponse.java
  src/main/java/com/linkode/api_server/service/LoginService.java
  src/main/java/com/linkode/api_server/service/MemberService.java
  src/main/java/com/linkode/api_server/util/JwtProvider.java
Labels: refactoring

#51 Fix: Member 객체 없을 시 컨트롤러에서 메세지로 반환하도록 수정
  src/main/java/com/linkode/api_server/controller/LoginController.java
  src/main/java/com/linkode/api_server/service/LoginService.java
Labels: fix

#52 Feat : memberStatus 를 추가로 반환 및 member 객체 null 에 대한 처리
  src/main/java/com/linkode/api_server/controller/LoginController.java
  src/main/java/com/linkode/api_server/dto/member/LoginResponse.java
  src/main/java/com/linkode/api_server/service/LoginService.java
Labels: Feat

#48 Refactor : 맴버 스터디룸 조회,탈퇴 리펙토링
  src/main/java/com/linkode/api_server/controller/StudyroomController.java
  src/main/java/com/linkode/api_server/repository/MemberstudyroomRepository.java
  src/main/java/com/linkode/api_server/service/MemberStudyroomService.java
Labels: refactoring

#53 Feat : 실시간 기능 API서버에서 분리
  .github/workflows/gradle.yml
  Dockerfile
  build.gradle
  src/main/java/com/linkode/api_server/config/RestTemplateConfig.java
  src/main/java/com/linkode/api_server/config/WebSocketConfig.java
  src/main/java/com/linkode/api_server/controller/DataController.java
  src/main/java/com/linkode/api_server/controller/SignalingController.java
  src/main/java/com/linkode/api_server/controller/WebhookController.java
  src/main/java/com/linkode/api_server/handler/StompHandler.java
  src/main/java/com/linkode/api_server/service/DataService.java
  src/main/java/com/linkode/api_server/service/GithubIssueService.java
  src/main/java/com/linkode/api_server/service/WebSocketSessionService.java
  src/main/java/com/linkode/api_server/util/BroadCaster.java
  src/main/resources/application.yml
Labels: Feature
